baseURL: http://www.triumphlarp.org/
title: TRIUMPH
defaultContentLanguage: en
languages:
  en:
    lang: en
    languageName: English
    weight: 1

MetaDataFormat: yaml

menu:
  main:
  - name: Home
    url: /index.html
    weight: 1
  - name: Practical
    url: /practical/
    weight: 2
  - name: FAQ
    url: /faq/
    weight: 3
